# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant cluster mode

# /etc/hosts in base box
# 192.168.233.18 master.perf.at15
# 192.168.233.19 slave1.perf.at15
# 192.168.233.20 slave2.perf.at15
# 192.168.233.21 slave3.perf.at15

Vagrant.configure("2") do |config|
  config.vm.define :master do |alpha|
    alpha.vm.box = "fedora/25-cloud-base"
    alpha.vm.network :private_network, ip: "192.168.233.18"
    alpha.vm.hostname = "master"
  end

  config.vm.define :slave1 do |beta|
    beta.vm.box = "fedora/25-cloud-base"
    beta.vm.network :private_network, ip: "192.168.233.19"
    beta.vm.hostname = "slave1"
  end

  config.vm.define :slave2 do |beta|
    beta.vm.box = "fedora/25-cloud-base"
    beta.vm.network :private_network, ip: "192.168.233.20"
    beta.vm.hostname = "slave2"
  end

end
