# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant base libvirt script

Vagrant.configure(2) do |config|

  # vagrant up --provider=libvirt
  config.vm.define :base do |base|
    base.vm.box = "fedora/25-cloud-base"
    # FIXME: bidirection using 9p won't work
    # base.vm.synced_folder './', '/vagrant', type: '9p', disabled: false, accessmode: "mapped", mount: false
    base.vm.provider :libvirt do |domain|
      domain.cpu_mode = "host-passthrough"
    end
  end

end
