# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant single node libvirt script

Vagrant.configure(2) do |config|

  config.vm.define :single do |sg|
    sg.vm.box = "fedora/25-cloud-base"
    sg.vm.network :private_network, ip: "192.168.233.17"
    sg.vm.hostname = "single"
    sg.vm.provider :libvirt do |domain|
      domain.cpu_mode = "host-passthrough"
      domain.memory = "4096"
    end
    # sg.vm.provision "shell", inline: <<-SHELL
    #   /vagrant/config.sh
    # SHELL
  end

end
