# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant single node libvirt script

Vagrant.configure(2) do |config|

  # vagrant up --provider=libvirt
  config.vm.define :single do |single|
    # FIXME: waiting for ssh to become avaliable .... ok ... I gave up
    single.vm.box = "at15/hadoop-spark-perf"
    # single.vm.box = "fedora/25-cloud-base"
    single.vm.provider :libvirt do |domain|
      domain.cpu_mode = "host-passthrough"
    end
  end

end
